version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: smarttable_postgres
    environment:
      POSTGRES_USER: ntunga
      POSTGRES_PASSWORD: gibesh2002
      POSTGRES_DB: smarttable
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ntunga"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
